### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by okagartria** [robsonvn/laravel-couchdb#11]
Hi there,

I have problem when using migrate command. 
php artisan migrate --force

I got this  message
In Builder.php line 72:
                                                                                  
  Call to undefined method Robsonvn\CouchDB\Schema\Grammar::compileTableExists()

**Comment by robsonvn** [comment]
Sorry for replying so late, I was on holidays.

In case you're trying to create/edit "table structure", you don't need to worry about it using Couch DB.

As we are talking about a NoSQL database which relays on documents not tables, we don't have migration implemented, though I understand we may need it in cases that we need to update documents.
