### ISSUE TITLE
Laravel Requests - Rules: UNIQUE

### ISSUE THREAD

**Issue by edukmattos** [robsonvn/laravel-couchdb#13]
HI !
Is this package works with Laravel Requests Rules ?
 My script:
public function rules()
    {
        return [
            'name' => 'required|max:40|unique:**users_collection**,name,'.**$this->_id**.',id,deleted_at,NULL',
            'fullname' => 'required|max:100|unique:**users_collection**,fullname,'.**$this->_id**.',id,deleted_at,NULL',
            'email' => 'required|email|max:50|unique:**users_collection**,email,'.**$this->_id**.',id,deleted_at,NULL',
            'role_id' => 'required'
        ];
    }
I created the same users and validation dont works !
Any suggestion ?

**Comment by edukmattos** [comment]
Sorry. I founded my error:
'name' => 'required|max:40|unique:users_collection,name,'.$this->_id.',**_id**,deleted_at,NULL',

**Comment by edukmattos** [comment]
My problem is that the laravel validation differentiates between upper and lower case characters, ie, CAR is different of the car. I need validation to consider CAR = car.
Any suggestions ?

**Comment by edukmattos** [comment]
My problem is that the laravel validation differentiates between upper and lower case characters, ie, CAR is different of the car. I need validation to consider CAR = car.
Any suggestions ?

**Comment by edukmattos** [comment]
Hi !
With MySQL it works and CouchDB does not.

**Comment by robsonvn** [comment]
Hi @ecmattos, 

I don't see this as a problem. CouchDB treat the fields as case-sensitive, hence CAR is not equals car. 

Why don't you treat your inputs before validating?

**Comment by robsonvn** [comment]
Either you start to store your data lower or upper case only or you will have to treatment your input before validating. 

Maybe this can help you 

'name' => Rule::unique('name')->where(function ($query) {
    $query->where('_id', strtoupper('car'));
})

**Comment by edukmattos** [comment]
It worked !
Thanks !
