### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by abedmaatalla** [robsonvn/laravel-couchdb#7]
InvalidArgumentException
'dbname' is a required option to create a CouchDBClient

**Comment by robsonvn** [comment]
Have you included in yours .env file 

DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=

?

**Comment by abedmaatalla** [comment]
yes 
DB_CONNECTION=couchdb
DB_HOST=127.0.0.1
DB_PORT=5984
DB_DATABASE=couchdb
DB_USERNAME=
DB_PASSWORD=

But i can create new documents but i can't retrieve them

**Comment by abedmaatalla** [comment]
this is not a big issue i pass this by adding dbname 

            'driver'   => 'couchdb',
            'type'       => 'socket',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 5984),
            'database' => env('DB_DATABASE'),

            'dbname' => env('DB_DATABASE'),

            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD')

also, I guess you have to add type = socket

**Comment by robsonvn** [comment]
Can you send me your composer.json ?

**Comment by abedmaatalla** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/robsonvn/couchdb-client"
        }
    ],
    "require": {
        "php": ">=5.6.4",
        "doctrine/couchdb": "dev-master",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "robsonvn/laravel-couchdb": "^1.5"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by robsonvn** [comment]
I'll create a boilerplate app then we can check.

**Comment by abedmaatalla** [comment]
does it work on your side?

**Comment by robsonvn** [comment]
Yeah, it's working in 3 projects I currently working on.
I guess I know the problem here, I'm creating a project from the scratch before confirm. 

In the mean while, can you add 
 "minimum-stability": "dev",
in your composer.json 

and run composer update?

**Comment by abedmaatalla** [comment]
Problem 1
    - The requested package minimum-stability could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by robsonvn** [comment]
This issue is solved by adding  'type' and 'database' in the database.php, I updated the docs, let's proceed this discussion on #8
