### ISSUE TITLE
Exception: QueryException Referer header required.

### ISSUE THREAD

**Issue by abedmaatalla** [robsonvn/laravel-couchdb#8]
When ever i call get() this error show up. when i took a look into your code i found your comment saying that you need to work more on it.

**Comment by robsonvn** [comment]
I'll wait for your response on #7 before going on this issue.

**Comment by abedmaatalla** [comment]
But i can create new documents but i can't retrieve them

**Comment by robsonvn** [comment]
There is another thing missing in the docs is that the CouchDB user must have admin privileges because only admins can create design docs (index). Are you using an admin user?

**Comment by abedmaatalla** [comment]
yes, I'm admin user .. i can create docs but it shows this issue when i want to retrieve 

> QueryException Referer header required.

**Comment by abedmaatalla** [comment]
can you please share one of your project's composer.js?

**Comment by robsonvn** [comment]
I have just created a boilerplate app, please check it out.

https://github.com/robsonvn/laravel-couchdb-boilerplate

**Comment by robsonvn** [comment]
I reckon there is something to do with your composer.json as well, please tell me if the boilerplate app works for you.

**Comment by abedmaatalla** [comment]
no it didn't work. still this error showing up 
`Exception
QueryException Referer header required.`

**Comment by abedmaatalla** [comment]
I can always create new docs but can't retrieve them

**Comment by robsonvn** [comment]
can you tell me your couchdb version

curl -X GET http://localhost:5984

**Comment by abedmaatalla** [comment]
> "version":"1.6.1","vendor":{"name":"Homebrew","version":"1.6.1_12"}

**Comment by robsonvn** [comment]
Oh yeah, currently this library only works with CouchDB 2.0+

**Comment by robsonvn** [comment]
In fact, I don't see this library supporting 1.x version because it relays on Mongo Query (/find endpoint) and it's only available on CouchDB 2

**Comment by robsonvn** [comment]
I'm closing this issue, I hope you can upgrade your CouchDB version.
