### ISSUE TITLE
FatalThrowableError

### ISSUE THREAD

**Issue by abedmaatalla** [robsonvn/laravel-couchdb#9]
> `Issue`
this error shows up when using embedsOne

Type error: Argument 2 passed to Robsonvn\CouchDB\Relations\EmbedsOneOrMany::match() must be an instance of Illuminate\Database\Eloquent\Collection

> `Documentation`

Change this part of documentation 
=> 
use Robsonvn\CouchDB\Eloquent\Model as Eloquent;

class User extends Eloquent {

    public function items()
    {
        return $this->hasMany(**'Item'**);
    }

}

To 
=> 
use Robsonvn\CouchDB\Eloquent\Model as Eloquent;

class User extends Eloquent {

    public function items()
    {
        return $this->hasMany(**Item::class**);
    }

}

**Comment by robsonvn** [comment]
You can specify the full path of the class as \App\Collection or the class itself
